language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs"
after_success:
  - ./build/travis-docs.sh
env:
  global:
    - secure: XQ3psu5eCkMM/Rctuw0xpY+ECFAj0sQoGcqKyHjey7NKBJzU1+Ae4SAJzsyjgm6MlsVgFLQdaeNJLQS7CT/TBc4Tn34BrzrbX9TrFmVyYjlJM7H07AKPWOQhcs2MV+gHnAFiQ1+jOgVGJ3/0a0jqRP9K4Hl1kR2fD1p/cQdpT/+t3yZmFu3K6SnnjNG8TXb7larOvTOziQBOX9nXVgEEJAWLo37LYWNcCBLDxN0PoNYhFEBa525Naj8z3szlXZedI63x8LVRQfPhXflanLxk+HqI+UfpSTkLc27KdGVuNpouDlAT8TOJtCzAX43m72e8nqNWe3CfDQHtZ9WJZKs3bPITicAgox1Cfyp5U61YRrF5jIC3YvkWYUhhy8eMwRdKIEgr6SVIE/mVoCqnYlCurVZziYIg2EUyCX71U/BC1E4e82yAxP3Y5kUf51lP0GRuLWI/FArw5RCS7V68GMCg0/+z3Evlv/fkAONY9Cnlejmoa0SiPsxVNl0W9RJkhpBhvmiRBi9NT00msu7vGakuNR1JqTlv/VPzG8vsvShcURQ/RhEPucqHV2YBvGiFIxmZy0IANnaMYjX8D9flt0tjMpCiTt75W2cyTxhP+d5DAiv8jaC5qH1mEkB1ZmGqrtp2ztiH3r9TW2FrArfeW38uCFPc+h30dRdSkA+Ct19lQ1A=
