language: node_js
node_js:
- '0.12'
- '0.10'
- iojs
after_success:
- "./build/travis-docs.sh"
env:
  global:
    - secure: W8kXNcyrizznI3LHID/knDQ8vs1gXyYKTB6+tg4sFQ4PGxxaSA6cTSNeXY7r0Z3R/GnmkqfAaa9umqt/i3XQwMGvf+LRuiClZ8Zqy/7hGHXAbsmgKXxqvIBJtZDb8Vqr15fKej14cuah9/9nDrPThuFAhw6+7JZvko4OQ80Q8ULKZjTZ//pWbgqp8oUzXj02x++dcMQDI2d26cOZxDHyurejz3g7/CK+NNWErn358Px+EN/unONtHOoqCHr2YQFBLMaCqpk9uF+rytNjQV2vA6nNCmdeRBT51xQepyvR/zUzpZN2CpSxKG1BK7iI5A5po/KfXK0lC98SDOudVHxqfP+jeYdZ+gaVwjSdp2ldPxJIPHJsTVNkvzsoTAHqZ+PvJ44PcmHer7dkRD9KWxoEPSVpQigIpsp7Q/2LO8pmfOPnVZgl/R2FGT29zLAv8CdzVaECHBobgWTkFnEG/rzddbKxBCYHn18YleJfrH9mzUp/S3ED1T5tbSpWuVP5NJMh00CdE3cAhDbedGShtWdJEwbR1xhrTwzaaw8zVACQ9A/u3TzfcNzXipOz31D63YSN/BEoUMuXh+Z+uhQeDGzuNMcI/Wzwag4PkLoWeyNNd9frKf01xI0spJQORGIW1wgEde96a/rex07kI+3FUjyiknFM6THYDkQZrst30MujDKA=
