language: node_js
node_js:
- '0.12'
- '0.10'
- iojs
after_success:
- "./build/travis-docs.sh"
env:
  global:
    - secure: OyXAp5JOfXppCiA7st5fY5e/BRYwZ6D/hjzX9pbiX6z4En9jty4KvUqCuZl32cymRS8ss5EmgTvlCyk3U63pEOCU/0TTIcuu17wH64dLIbW0t1lm1Rop//k7ZbsgtrsWZDSlRwlLqmkmObe4ejLknmNA+Gst9CoGnMpI4Ls0dUhOm80BFCPV40QxuijtaKdIxEtSeqGANwCTBMsDgVWiv/Ba4y2uWHzmrwiw9J3klu9hCdMc20/rLwRci7oPl8y2JCTbISbajyS+OhnruGohWaYz5YSQsIXekcOFC/tMVOcg6Rzv15lVAfS1VAvL6UIrzV693JQBCq9m43OiuZyQUrREDo0hTxsvPy3NsNHgfREYTya9NdF5Bbjl1OEVPLlTjy4DkAPmgkBLBeV5e/vvitfmwF18KssfGgnqLM4oLSroO5pYfRqzcXg0aIKhsZi6RABTDy3aT5exA5M9ShXjF/jtaE5fMB3sNlcWk+LKSIY0F0IJaeIKwTkQoKHcAXBoFqPCWvlcSOHLz9aLzhW/ewHt0R8pixtKZiWVVlWtA+CV0BWjFEsOuy7vk8MDmatIIY0D5jaLq9OuXyoTZ9Ly6uG/xfsk1Wsy4IqZtphTEc76DN+u/Vqo+eHlEEbOhfjlfOPAWcrc+kJoc3CnGBHNOQfmj5liKwc/CEDbi3jLzuc=
